export default {
    header: "UNIFYING NFT SPACE AND ESPORTS",
    text: "ORBEEM - IS AN NFT PLATFORM CONNECTING THE NFT WORLD AND ESPORTS. SIMILAR TO PLAY-TO-EARN PROJECTS WE GIVE OUR USERS A CHANCE TO EARN REWARDS FOR PLAYING VARIOUS GAMES. THE WHOLE SYSTEM IS BASED ON OUR NFT MARKETPLACE. ALL YOU NEED TO START EARNING IS TO PURCHASE AN NFT FOR YOUR GAME OF CHOICE, LINK YOUR GAME ACCOUNT TO ORBEEM AND START PLAYING! ",
    image: "/image_info.webp"
}