export default {
    header: 'ORBEEM ESPORTS\n PLAY-TO-EARN\n NFT PLATFORM',
    text: 'WITH THE EMEREGENCE OF VARIOUS NFT MARKETPLACES THE NEXT TREND IN THE NFT WORLD IS PLAY-TO-EARN PLATFORMSORBEEM - IS THE BRIDGE BETWEEN ESPORTS AND NFT SPACE WE OFFER OUR USERS TO EARN REWARDS FOR THEIR VICTORIES',
    image: '/welcome.webp'
}