export default {
    header: 'ORBEEM \n Play-to-Earn \nGame-Fi\n Metaverse',
    text: 'WITH THE EMEREGENCE OF VARIOUS NFT MARKETPLACES THE NEXT TREND IN THE NFT WORLD IS PLAY-TO-EARN PLATFORMSORBEEM - IS THE BRIDGE BETWEEN ESPORTS AND NFT SPACE WE OFFER OUR USERS TO EARN REWARDS FOR THEIR VICTORIES',
    image: '/welcome.webp'
}